name: Build LaTeX CV

on:
  push:
    branches: [main]
    paths:
      - "LateX/**"
      - ".github/workflows/build_latex.yml"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk

      - name: Compile LaTeX Document
        run: |
          cd LateX
          latexmk -xelatex -interaction=nonstopmode -file-line-error main.tex

      - name: Rename PDF
        run: mv LateX/main.pdf LateX/Jerry_Chen_CV.pdf

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: latest
          files: LateX/Jerry_Chen_CV.pdf
          body: "Latest compiled CV from main branch."
          token: ${{ secrets.GITHUB_TOKEN }}
